INSERT INTO paises (id, pais, capital, codigo) VALUES(1, 'Argentina', 'Buenos Aires', 'AR');
INSERT INTO paises (id, pais, capital, codigo) VALUES(2, 'Bolivia', 'Sucre', 'BO');
INSERT INTO paises (id, pais, capital, codigo) VALUES(3, 'Brasil', 'Brasilia', 'BR');
INSERT INTO paises (id, pais, capital, codigo) VALUES(4, 'Chile', 'Santiago', 'CL');
INSERT INTO paises (id, pais, capital, codigo) VALUES(5, 'Colombia', 'Bogotá', 'CO');
INSERT INTO paises (id, pais, capital, codigo) VALUES(6, 'Ecuador', 'Quito', 'EC');
INSERT INTO paises (id, pais, capital, codigo) VALUES(7, 'Guyana', 'Georgetown', 'GY');
INSERT INTO paises (id, pais, capital, codigo) VALUES(8, 'Paraguay', 'Asunción', 'PY');
INSERT INTO paises (id, pais, capital, codigo) VALUES(9, 'Perú', 'Lima', 'PE');
INSERT INTO paises (id, pais, capital, codigo) VALUES(10, 'Surinam', 'Paramaribo', 'SR');
INSERT INTO paises (id, pais, capital, codigo) VALUES(11, 'Uruguay', 'Montevideo', 'UY');
INSERT INTO paises (id, pais, capital, codigo) VALUES(12, 'Venezuela', 'Caracas', 'VE');